volumes:
  pg_data:
  backend_static:
  media:

networks:  # Добавить объявление сети
  kittygram-net:
    driver: bridge

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - kittygram-net  # Явное подключение к сети

  backend:
    networks:
      - kittygram-net
    build: ./backend/
    env_file: .env
    volumes:
      - backend_static:/app/backend_static  # Изменён путь
      - media:/app/media
    command: gunicorn kittygram_backend.wsgi:application --bind 0.0.0.0:8000  # Исправлено на gunicorn

  frontend:
    networks:
      - kittygram-net
    build: ./frontend/
    volumes:
      - backend_static:/app/backend_static  # Изменён путь
    command: sh -c "npm run build && cp -r /app/build/* /app/backend_static/"

  gateway:
    networks:
      - kittygram-net
    build: ./nginx/
    env_file: .env
    ports:
      - "80:80"
      - "443:443"  # Добавлен проброс порта HTTPS
    volumes:
      - backend_static:/static  # Исправлено на /static
      - media:/media
      - ./certs:/etc/letsencrypt  # Добавлен том для сертификатов
    depends_on:
      - backend
      - frontend