version: '3'

volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data

  backend:
    image: denisbelikov/kittygram_backend
    env_file: .env
    volumes:
      - static_volume:/static
      - media_volume:/media
    depends_on:
      - db
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - STATIC_URL=/backend_static/
      - STATIC_ROOT=/static/collected_static
    command: sh -c "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn kittygram_backend.wsgi:application --bind 0.0.0.0:8000"

  frontend:
    image: denisbelikov/kittygram_frontend
    env_file: .env
    command: mkdir -p /static/frontend/ && cp -r /app/build/. /static/frontend/
    volumes:
      - static_volume:/static

  gateway:
    image: denisbelikov/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static_volume:/static
      - media_volume:/media
    depends_on:
      - backend
      - frontend
